name: Build
on: [ push, pull_request, merge_group ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
      - uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          gradle-home-cache-excludes: |
            gradle.properties
      - run: ./gradlew build publishToMavenLocal --stacktrace
      - uses: actions/upload-artifact@v3
        with:
          name: Maven Local
          path: ~/.m2/repository